### ISSUE TITLE
keresésnél tárgymutató találat

### ISSUE THREAD

**Issue by rrd108** [borsosl/Vidyavana#1]
Keresésnél szerintem felesleges megjeleníteni azokat a találatokat amelyeket a tárgymutatóban talál, hiszen ezeket úgyis megtalálja ott ahová a tárgymutató mutat.

**Comment by borsosl** [comment]
Ugyanakkor kiemeli a lényegeseket, ha sok találat van. Lehet nagyon alacsony boost-re is venni, hogy a végére kerüljön, és akkor meg lehet állni ha odaérsz.

**Comment by rrd108** [comment]
Vagy a súlyozásnál figyelembe veszed, hogy ha szerepel a tárgymutatóban is akkor az nagyobb súlyú.

**Comment by borsosl** [comment]
#51 követi ezután.
