### ISSUE TITLE
több mint 100 keresési találat esetén a 100 felettiekre nem lehet lapozni

### ISSUE THREAD

**Issue by rrd108** [borsosl/Vidyavana#2]
Ha több mint 100 találat van és egyesével lapozok, akkor a 100. után nem lapoz tovább és hibaüzenetet dob.

Hiba történt. Kérlek írj hibajelentést arról, hogy melyik funkciót használtad és hogyan. Hivatkozz erre a referenciaszámra: 4.

**Comment by borsosl** [comment]
Ez csak nincs még kész. :)
