### ISSUE TITLE
Kézi, nevesített könyvjelző

### ISSUE THREAD

**Issue by borsosl** [borsosl/Vidyavana#27]
Az automatikus könyvjelző nem írja az adatbázist, csak egy gyors cookie. A tárolt könyvjelző nem módosul állandóan, és másik eszközön is meglesz.
- default nevében dátum,könyv,fej,vers
- tárolja a scroll pozíciót is ha hosszú fejezet

**Comment by rrd108** [comment]
Ha esetleg a program rá tudna kérdezni, hogy szeretném-e onnan folytatni az olvasást az adott könyvnél, ahol abbahagytam, az nagyon szimpatikus funkció lenne.

**Comment by borsosl** [comment]
Inkább az Automatikus könyvjelző #26 lenne kiterjesztve úgy, hogy könyvenként 1 mutatót tároljon. Ugyanakkor nehéz automatikusan megkülönböztetni a keresést és az olvasást.

**Comment by borsosl** [comment]
A scroll pozíció tárolása még nem megoldott, külön enhancement lesz későbbre tervezve.
