### ISSUE TITLE
loader ikon megjelenítése bármilyen ajax requesthez

### ISSUE THREAD

**Issue by rrd108** [borsosl/Vidyavana#3]
A lapozás nagyon jól és gyorsan ment. A 100 találat végiglapozásakor átlagban 219 ms volt a válasz idő 154 ms volt a minimum és 997 ms a maximum.

Szerintem jó lenne megjeleníteni egy ajax loadert ha mondjuk pl több mint 400 ms a válasz. 100-ból 2 esetben volt 900 felett, 3 esetben 400 felett, a maradék 95 alatta volt.

**Comment by borsosl** [comment]
Lesz egy popup, amivel cancelezhetővé tenném az ajaxot, ha neadjisten beragadna a válasz. Mivel nem engedek újabb requestet, amíg az előző vissza nem jött.
