### ISSUE TITLE
keresésnél lapozás elhelyezése

### ISSUE THREAD

**Issue by rrd108** [borsosl/Vidyavana#4]
Mivel a találatokat tartalmazó szakaszok különböző hosszúságúak a lapozó függőleges helyzete is mindig más. Ha az ember böngészget akkor kicsit nehézkes, hogy fel le kell egerezni (márha a szerencsétlen nem billentyűvel lapoz...).

Javaslat 1: A lapozót fel lehetne tenni csak ikon formában a fejléc jobb felső részébe.

Javaslat 2: Kéne egy fix láblé és betenni a lapozót oda.

Nem tudom, hogy usability szempontból melyik a jobb.

**Comment by borsosl** [comment]
1. A fejléc keskeny és nehézkes telón rászúrni az ikonra. Ezzel együtt fogom oda is tenni.
2. A fix láblécen is gondolkodtam, de az telón túl sok helyet vesz el a szövegtől. Főleg ha valaki olyan nagy betűket szeret olvasni, mint én.

**Comment by borsosl** [comment]
A fejlécbe került, talán 32px-ről 48-ra kéne venni a fejlécet, és akkor telón is jó.

**Comment by borsosl** [comment]
Magasabb lett a fejléc, hogy a lapozó gombokra lehessen érinteni.
