### ISSUE TITLE
Keresésnél lapozható találati lista

### ISSUE THREAD

**Issue by rrd108** [borsosl/Vidyavana#59]
Jó lenne ha a keresésnél kapnánk egy találati listát, hogy ha csak valamire vagyok kívánsi akkor abból is ki tudjam választani, ne kelljen végiglépdelni a találatokon.

**Comment by borsosl** [comment]
Ez korábban is felvetette azt a kérdést, hogy 1-1 bekezdésből mekkora szeletet mutatunk meg a találat körül, melyik találat körül, és hogy ez mobilon hogy tud kinézni. Ezért maradt a mostani megoldás.

**Comment by rrd108** [comment]
Talán könyvcím és versszám + előtte két szó + utána két szó?
