### ISSUE TITLE
Admin / felhasználók felületen változó oszlopszélességű táblázat, scroll

### ISSUE THREAD

**Issue by rrd108** [borsosl/Vidyavana#60]
Ha az emailcím hosszabb (pl goloka-pati@..) akkor az a sor becsúszik a következő mögé és így nem lehet szerkeszteni

**Comment by borsosl** [comment]
Kisebb zoom és desktop esetén nincs olyan sok probléma. :)

**Comment by borsosl** [comment]
Sima html táblázatként a böngésző intézi az oszlopszélességet. Scroll lehetővé teszi, hogy akár mobilon is kezelhető legyen.
