### ISSUE TITLE
A szakasz választó lenyíló mezői mobilon túl nagy betűvel jelennek meg - rövidítési opció

### ISSUE THREAD

**Issue by rrd108** [borsosl/Vidyavana#64]
a telefonos változat miatt jobb lenne, ha pl. a Bhg. fejezetek száma számmal van kiírva, nem betűvel. Így hosszúak a fejezet címek (főleg a tizedik után) és sokat kell legörgetni. És nagyon nagy a felugró fejezet címeinél a betűméret.

**Comment by borsosl** [comment]
Mit értesz "felugró fejezet" alatt?
Relatív betűméretek vannak, és a fejezetcím nagyobb, ahogy a könyvekben is.
A mobil változatban a zoomolás le van tiltva, a bázis fontméret módosítását máshogy kell megoldani, másik issue már fel van véve.

**Comment by rrd108** [comment]
Manjari mataji küldte ezt az észrevételt. Szerintem arra gondolt, hogy ha könyvet vagy fejezetet választok akkor a selectben nagyok a betűk mobilon.

**Comment by borsosl** [comment]
Mobil probléma esetén lécci az eszköz nevét is kérd el.

**Comment by borsosl** [comment]
Részben megoldja az, hogy találati lista esetén nincs ott a hosszú referencia, később felhasználói profilból kérhető lesz, hogy sehol ne írjon hosszút

**Comment by rrd108** [comment]
Egységes legyen a menüben lévővel
Ha rákattint akkor vált a rövid és hosszú között
Ha váltás után látszik akkor hogyan kezeljük?
Profil oldalon user setting, hogy mindent hosszan, mindent röviden vagy csak a könyv címet hosszan akarja látni, szakasz nézet tetején kell-e? és melyik verziója?
