### ISSUE TITLE
Utoljára olvasott könyvek automatikus könyvjelzőinek menüje

### ISSUE THREAD

**Issue by rrd108** [borsosl/Vidyavana#69]
Van, hogy bhakták több könyvet is olvasnak egyszerre, én is szoktam.  
Lehetne egy olyan menü, hogy  "jelenleg olvasott könyvek", és azon belül csak kattintani kellene, hogy melyik, és egyből ott lenne, ahol abbahagytam.

**Comment by borsosl** [comment]
#26

**Comment by borsosl** [comment]
#26 és #27 után, előbb a működésük módja legyen kitalálva
